[build]
  publish = "."
  command = "echo 'Build complete'"

[[redirects]]
  from = "/pitch-deck/*"
  to = "/pitch-deck/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200