[package]
name = "kaseddie_executor"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.3"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
# See more keys and their definitions at https://foundry-rs.github.io/starknet-foundry/appendix/snforge-toml.html